# Allow local connections
local   all             all                                     trust
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256

# Allow all Docker internal network connections (app + pgbouncer)
host    all             all             172.0.0.0/8             scram-sha-256

# Allow streaming replication from any Docker container
host    replication     replicator      172.0.0.0/8             scram-sha-256
